name: CI

on:
  push:
  pull_request:

jobs:
  frontend:
    name: Frontend (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        working-directory: web
        run: npm ci

      - name: Type check
        working-directory: web
        run: npx tsc -b --noEmit

      - name: Build
        working-directory: web
        env:
          BASE_PATH: "/werkstatt/"
          VITE_USE_MOCK: "1"
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist-node${{ matrix.node }}
          path: web/dist

  validate_payloads:
    name: Validate JSON payloads
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validate JSON payloads against schema
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema
          python scripts/validate_payloads.py
