[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Single Page App redirect to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
